/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SpeakingRouteImport } from './routes/speaking'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as IntelRouteImport } from './routes/intel'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdvisoryRouteImport } from './routes/advisory'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvisoryIndexRouteImport } from './routes/advisory.index'
import { Route as StudioSplatRouteImport } from './routes/studio.$'
import { Route as StoriesSlugRouteImport } from './routes/stories.$slug'
import { Route as SpeakingSlugRouteImport } from './routes/speaking.$slug'
import { Route as ReportsSlugRouteImport } from './routes/reports.$slug'
import { Route as IntelSlugRouteImport } from './routes/intel.$slug'
import { Route as AdvisorySlugRouteImport } from './routes/advisory.$slug'
import { Route as StoriesSeriesSeriesSlugRouteImport } from './routes/stories.series.$seriesSlug'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakingRoute = SpeakingRouteImport.update({
  id: '/speaking',
  path: '/speaking',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelRoute = IntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisoryRoute = AdvisoryRouteImport.update({
  id: '/advisory',
  path: '/advisory',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisoryIndexRoute = AdvisoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdvisoryRoute,
} as any)
const StudioSplatRoute = StudioSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => StudioRoute,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StoriesRoute,
} as any)
const SpeakingSlugRoute = SpeakingSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SpeakingRoute,
} as any)
const ReportsSlugRoute = ReportsSlugRouteImport.update({
  id: '/reports/$slug',
  path: '/reports/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelSlugRoute = IntelSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => IntelRoute,
} as any)
const AdvisorySlugRoute = AdvisorySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdvisoryRoute,
} as any)
const StoriesSeriesSeriesSlugRoute = StoriesSeriesSeriesSlugRouteImport.update({
  id: '/series/$seriesSlug',
  path: '/series/$seriesSlug',
  getParentRoute: () => StoriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory': typeof AdvisoryRouteWithChildren
  '/contact': typeof ContactRoute
  '/intel': typeof IntelRouteWithChildren
  '/labs': typeof LabsRoute
  '/privacy': typeof PrivacyRoute
  '/speaking': typeof SpeakingRouteWithChildren
  '/stories': typeof StoriesRouteWithChildren
  '/studio': typeof StudioRouteWithChildren
  '/advisory/$slug': typeof AdvisorySlugRoute
  '/intel/$slug': typeof IntelSlugRoute
  '/reports/$slug': typeof ReportsSlugRoute
  '/speaking/$slug': typeof SpeakingSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/studio/$': typeof StudioSplatRoute
  '/advisory/': typeof AdvisoryIndexRoute
  '/stories/series/$seriesSlug': typeof StoriesSeriesSeriesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/intel': typeof IntelRouteWithChildren
  '/labs': typeof LabsRoute
  '/privacy': typeof PrivacyRoute
  '/speaking': typeof SpeakingRouteWithChildren
  '/stories': typeof StoriesRouteWithChildren
  '/studio': typeof StudioRouteWithChildren
  '/advisory/$slug': typeof AdvisorySlugRoute
  '/intel/$slug': typeof IntelSlugRoute
  '/reports/$slug': typeof ReportsSlugRoute
  '/speaking/$slug': typeof SpeakingSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/studio/$': typeof StudioSplatRoute
  '/advisory': typeof AdvisoryIndexRoute
  '/stories/series/$seriesSlug': typeof StoriesSeriesSeriesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory': typeof AdvisoryRouteWithChildren
  '/contact': typeof ContactRoute
  '/intel': typeof IntelRouteWithChildren
  '/labs': typeof LabsRoute
  '/privacy': typeof PrivacyRoute
  '/speaking': typeof SpeakingRouteWithChildren
  '/stories': typeof StoriesRouteWithChildren
  '/studio': typeof StudioRouteWithChildren
  '/advisory/$slug': typeof AdvisorySlugRoute
  '/intel/$slug': typeof IntelSlugRoute
  '/reports/$slug': typeof ReportsSlugRoute
  '/speaking/$slug': typeof SpeakingSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/studio/$': typeof StudioSplatRoute
  '/advisory/': typeof AdvisoryIndexRoute
  '/stories/series/$seriesSlug': typeof StoriesSeriesSeriesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advisory'
    | '/contact'
    | '/intel'
    | '/labs'
    | '/privacy'
    | '/speaking'
    | '/stories'
    | '/studio'
    | '/advisory/$slug'
    | '/intel/$slug'
    | '/reports/$slug'
    | '/speaking/$slug'
    | '/stories/$slug'
    | '/studio/$'
    | '/advisory/'
    | '/stories/series/$seriesSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/intel'
    | '/labs'
    | '/privacy'
    | '/speaking'
    | '/stories'
    | '/studio'
    | '/advisory/$slug'
    | '/intel/$slug'
    | '/reports/$slug'
    | '/speaking/$slug'
    | '/stories/$slug'
    | '/studio/$'
    | '/advisory'
    | '/stories/series/$seriesSlug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advisory'
    | '/contact'
    | '/intel'
    | '/labs'
    | '/privacy'
    | '/speaking'
    | '/stories'
    | '/studio'
    | '/advisory/$slug'
    | '/intel/$slug'
    | '/reports/$slug'
    | '/speaking/$slug'
    | '/stories/$slug'
    | '/studio/$'
    | '/advisory/'
    | '/stories/series/$seriesSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvisoryRoute: typeof AdvisoryRouteWithChildren
  ContactRoute: typeof ContactRoute
  IntelRoute: typeof IntelRouteWithChildren
  LabsRoute: typeof LabsRoute
  PrivacyRoute: typeof PrivacyRoute
  SpeakingRoute: typeof SpeakingRouteWithChildren
  StoriesRoute: typeof StoriesRouteWithChildren
  StudioRoute: typeof StudioRouteWithChildren
  ReportsSlugRoute: typeof ReportsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speaking': {
      id: '/speaking'
      path: '/speaking'
      fullPath: '/speaking'
      preLoaderRoute: typeof SpeakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel': {
      id: '/intel'
      path: '/intel'
      fullPath: '/intel'
      preLoaderRoute: typeof IntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisory': {
      id: '/advisory'
      path: '/advisory'
      fullPath: '/advisory'
      preLoaderRoute: typeof AdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisory/': {
      id: '/advisory/'
      path: '/'
      fullPath: '/advisory/'
      preLoaderRoute: typeof AdvisoryIndexRouteImport
      parentRoute: typeof AdvisoryRoute
    }
    '/studio/$': {
      id: '/studio/$'
      path: '/$'
      fullPath: '/studio/$'
      preLoaderRoute: typeof StudioSplatRouteImport
      parentRoute: typeof StudioRoute
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/speaking/$slug': {
      id: '/speaking/$slug'
      path: '/$slug'
      fullPath: '/speaking/$slug'
      preLoaderRoute: typeof SpeakingSlugRouteImport
      parentRoute: typeof SpeakingRoute
    }
    '/reports/$slug': {
      id: '/reports/$slug'
      path: '/reports/$slug'
      fullPath: '/reports/$slug'
      preLoaderRoute: typeof ReportsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel/$slug': {
      id: '/intel/$slug'
      path: '/$slug'
      fullPath: '/intel/$slug'
      preLoaderRoute: typeof IntelSlugRouteImport
      parentRoute: typeof IntelRoute
    }
    '/advisory/$slug': {
      id: '/advisory/$slug'
      path: '/$slug'
      fullPath: '/advisory/$slug'
      preLoaderRoute: typeof AdvisorySlugRouteImport
      parentRoute: typeof AdvisoryRoute
    }
    '/stories/series/$seriesSlug': {
      id: '/stories/series/$seriesSlug'
      path: '/series/$seriesSlug'
      fullPath: '/stories/series/$seriesSlug'
      preLoaderRoute: typeof StoriesSeriesSeriesSlugRouteImport
      parentRoute: typeof StoriesRoute
    }
  }
}

interface AdvisoryRouteChildren {
  AdvisorySlugRoute: typeof AdvisorySlugRoute
  AdvisoryIndexRoute: typeof AdvisoryIndexRoute
}

const AdvisoryRouteChildren: AdvisoryRouteChildren = {
  AdvisorySlugRoute: AdvisorySlugRoute,
  AdvisoryIndexRoute: AdvisoryIndexRoute,
}

const AdvisoryRouteWithChildren = AdvisoryRoute._addFileChildren(
  AdvisoryRouteChildren,
)

interface IntelRouteChildren {
  IntelSlugRoute: typeof IntelSlugRoute
}

const IntelRouteChildren: IntelRouteChildren = {
  IntelSlugRoute: IntelSlugRoute,
}

const IntelRouteWithChildren = IntelRoute._addFileChildren(IntelRouteChildren)

interface SpeakingRouteChildren {
  SpeakingSlugRoute: typeof SpeakingSlugRoute
}

const SpeakingRouteChildren: SpeakingRouteChildren = {
  SpeakingSlugRoute: SpeakingSlugRoute,
}

const SpeakingRouteWithChildren = SpeakingRoute._addFileChildren(
  SpeakingRouteChildren,
)

interface StoriesRouteChildren {
  StoriesSlugRoute: typeof StoriesSlugRoute
  StoriesSeriesSeriesSlugRoute: typeof StoriesSeriesSeriesSlugRoute
}

const StoriesRouteChildren: StoriesRouteChildren = {
  StoriesSlugRoute: StoriesSlugRoute,
  StoriesSeriesSeriesSlugRoute: StoriesSeriesSeriesSlugRoute,
}

const StoriesRouteWithChildren =
  StoriesRoute._addFileChildren(StoriesRouteChildren)

interface StudioRouteChildren {
  StudioSplatRoute: typeof StudioSplatRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioSplatRoute: StudioSplatRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvisoryRoute: AdvisoryRouteWithChildren,
  ContactRoute: ContactRoute,
  IntelRoute: IntelRouteWithChildren,
  LabsRoute: LabsRoute,
  PrivacyRoute: PrivacyRoute,
  SpeakingRoute: SpeakingRouteWithChildren,
  StoriesRoute: StoriesRouteWithChildren,
  StudioRoute: StudioRouteWithChildren,
  ReportsSlugRoute: ReportsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
